#!/usr/bin/env npx tsx
/**
 * PNG-to-Pattern converter for LedWall sprite overlays.
 *
 * Usage:
 *   npx tsx scripts/png-to-pattern.ts <input.png> [output-name]
 *   npx tsx scripts/png-to-pattern.ts assets/my-sprite.png my-sprite
 *
 * Input:  A PNG image that will be resized to 24×48.
 *         Non-black pixels (brightness > 30%) become sprite LEDs (true).
 *         Black/dark pixels become background LEDs (false).
 *
 * For animated patterns, pass multiple PNGs:
 *   npx tsx scripts/png-to-pattern.ts frame1.png frame2.png frame3.png my-anim --fps=4
 *
 * Output: src/patterns/<name>.ts with a LedPattern export.
 */

import sharp from "sharp";
import { writeFileSync } from "fs";
import { resolve, basename } from "path";

const COLS = 24;
const ROWS = 48;
const BRIGHTNESS_THRESHOLD = 0.30; // pixels brighter than 30% → sprite LED

async function pngToGrid(filePath: string): Promise<boolean[][]> {
  const { data, info } = await sharp(filePath)
    .resize(COLS, ROWS, { fit: "fill" })
    .greyscale()
    .raw()
    .toBuffer({ resolveWithObject: true });

  const grid: boolean[][] = [];
  for (let r = 0; r < ROWS; r++) {
    const row: boolean[] = [];
    for (let c = 0; c < COLS; c++) {
      const idx = r * info.width + c;
      const brightness = data[idx] / 255;
      row.push(brightness > BRIGHTNESS_THRESHOLD);
    }
    grid.push(row);
  }
  return grid;
}

function gridToLiteral(grid: boolean[][]): string {
  const lines = grid.map(
    (row) => "    [" + row.map((v) => (v ? "1" : "0")).join(",") + "]"
  );
  return "  [\n" + lines.join(",\n") + "\n  ]";
}

async function main() {
  const args = process.argv.slice(2);
  if (args.length === 0) {
    console.error("Usage: npx tsx scripts/png-to-pattern.ts <input.png> [name] [--fps=N]");
    process.exit(1);
  }

  // Parse args: PNGs, name, --fps
  const pngFiles: string[] = [];
  let name = "";
  let fps = 4;

  for (const arg of args) {
    if (arg.startsWith("--fps=")) {
      fps = parseInt(arg.slice(6), 10);
    } else if (arg.endsWith(".png") || arg.endsWith(".PNG")) {
      pngFiles.push(arg);
    } else {
      name = arg;
    }
  }

  if (pngFiles.length === 0) {
    console.error("Error: No PNG files provided.");
    process.exit(1);
  }

  if (!name) {
    name = basename(pngFiles[0], ".png").replace(/[^a-zA-Z0-9-_]/g, "-");
  }

  // Convert PNGs to grids
  const frames: boolean[][][] = [];
  for (const file of pngFiles) {
    console.log(`Processing: ${file}`);
    frames.push(await pngToGrid(file));
  }

  // Generate TypeScript
  const isAnimated = frames.length > 1;
  const exportName = name.replace(/-([a-z])/g, (_, c) => c.toUpperCase()) + "Pattern";

  let ts = `import { LedPattern } from "../components/LedWall";\n\n`;
  ts += `// Generated by scripts/png-to-pattern.ts\n`;
  ts += `export const ${exportName}: LedPattern = {\n`;
  ts += `  frames: [\n`;
  for (const grid of frames) {
    ts += gridToLiteral(grid) + ",\n";
  }
  ts += `  ],\n`;
  if (isAnimated) {
    ts += `  fps: ${fps},\n`;
  }
  ts += `};\n`;

  const outPath = resolve(__dirname, "..", "src", "patterns", `${name}.ts`);
  writeFileSync(outPath, ts);
  console.log(`\nWritten: ${outPath}`);
  console.log(`Export:  ${exportName}`);
  console.log(`Frames:  ${frames.length}${isAnimated ? ` @ ${fps}fps` : " (static)"}`);

  // Count sprite LEDs for verification
  const spriteCount = frames[0].flat().filter(Boolean).length;
  const total = ROWS * COLS;
  console.log(`LEDs:    ${spriteCount}/${total} sprite (${((spriteCount / total) * 100).toFixed(1)}%)`);
  console.log(`\nDon't forget to add it to src/patterns/index.ts!`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
